from datetime import date
import models

sample_customers = [
    models.Customer(name="Alice Smith",      email="alice@example.com",
                    state="California", country="USA",   dob=date(1985, 4, 12)),
    models.Customer(name="Bob Johnson",      email="bob@example.com",
                    state="California", country="USA",   dob=date(1990, 7, 23)),
    models.Customer(name="Charlie Williams", email="charlie@example.com",
                    state="California", country="USA",   dob=date(1978, 1, 30)),
    models.Customer(name="Diana Brown",      email="diana@example.com",
                    state="California", country="USA",   dob=date(1982, 9, 15)),

    models.Customer(name="Evan Jones",       email="evan@example.com",
                    state="Texas",      country="USA",   dob=date(1995, 3, 8)),
    models.Customer(name="Fiona Garcia",     email="fiona@example.com",
                    state="Texas",      country="USA",   dob=date(1988, 12, 2)),
    models.Customer(name="George Miller",    email="george@example.com",
                    state="Texas",      country="USA",   dob=date(1975, 6, 20)),
    models.Customer(name="Hannah Davis",     email="hannah@example.com",
                    state="Texas",      country="USA",   dob=date(1993, 11, 27)),

    models.Customer(name="Ian Wilson",       email="ian@example.com",
                    state="New York",   country="USA",   dob=date(1980, 2, 14)),
    models.Customer(name="Julia Taylor",     email="julia@example.com",
                    state="New York",   country="USA",   dob=date(1987, 5, 5)),
    models.Customer(name="Kevin Anderson",   email="kevin@example.com",
                    state="New York",   country="USA",   dob=date(1992, 8, 19)),
    models.Customer(name="Linda Thomas",     email="linda@example.com",
                    state="New York",   country="USA",   dob=date(1979, 10, 31)),

    models.Customer(name="Mike Jackson",     email="mike@example.com",
                    state="Florida",    country="USA",   dob=date(1984, 1, 9)),
    models.Customer(name="Nina White",       email="nina@example.com",
                    state="Florida",    country="USA",   dob=date(1991, 4, 22)),
    models.Customer(name="Oliver Harris",    email="oliver@example.com",
                    state="Florida",    country="USA",   dob=date(1976, 7, 13)),
    models.Customer(name="Paula Martin",     email="paula@example.com",
                    state="Florida",    country="USA",   dob=date(1989, 9, 3)),

    models.Customer(name="Quentin Thompson", email="quentin@example.com",
                    state="Washington", country="USA",   dob=date(1977, 2, 28)),
    models.Customer(name="Rachel Garcia",    email="rachel@example.com",
                    state="Washington", country="USA",   dob=date(1983, 6, 17)),
    models.Customer(name="Steven Martinez",  email="steven@example.com",
                    state="Washington", country="USA",   dob=date(1994, 12, 24)),
    models.Customer(name="Tina Robinson",    email="tina@example.com",
                    state="Washington", country="USA",   dob=date(1986, 3, 11)),

    models.Customer(name="Uma Clark",        email="uma@example.com",
                    state="Ontario",    country="Canada", dob=date(1990, 5, 30)),
    models.Customer(name="Victor Rodriguez", email="victor@example.com",
                    state="Ontario",    country="Canada", dob=date(1981, 8, 8)),
    models.Customer(name="Wendy Lewis",      email="wendy@example.com",
                    state="Ontario",    country="Canada", dob=date(1974, 11, 2)),
    models.Customer(name="Xander Lee",       email="xander@example.com",
                    state="Quebec",     country="Canada", dob=date(1993, 1, 21)),
    models.Customer(name="Yvonne Walker",    email="yvonne@example.com",
                    state="Quebec",     country="Canada", dob=date(1992, 11, 5)),
]
